name: Update PDF Guide

on:
  push:
    branches:
    - master
    paths:
    - 'docs/*'
jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: maxheld83/pandoc@v2
        with:
          args: "-o Guia.pdf --variable urlcolor=cyan docs/index.md docs/sobre.md docs/transcricoes.md docs/numeros_numerais.md docs/unidades_medida.md docs/aspas_direto.md docs/citacoes.md docs/termos_estrangeiros.md docs/sons.md docs/mudanca_idioma.md docs/entrevistas.md docs/quebras.md docs/sincronia.md docs/tedx.md docs/acordo.md docs/onomatopeias.md docs/equivocos.md docs/glossario.md docs/ferramentas.md"
      - uses: actions/upload-artifact@master
        with:
          name: Guia
          path: Guia.pdf
      - uses: stefanzweifel/git-auto-commit-action@v2.0.0
        with:
          commit_author_email: tupaschoal@users.noreply.github.com
          commit_author_name: tupaschoal
          commit_message: Update Guia.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
