name: Document Conversion

on: push

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: INPUT_FILES=$(cat util/pdf_file_list.md)
      - uses: maxheld83/pandoc@v2
        with:
          args: "-o Guia.pdf --variable urlcolor=cyan ${INPUT_FILES}"
      - uses: actions/upload-artifact@master
        with:
          name: Guia.pdf
          path: Guia.pdf
